import 'package:flutter/material.dart';

/// Класс для локализации
class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations)!;
  }

  // Переводы
  static const Map<String, Map<String, String>> _localizedValues = {
    'ru': {
      'app_title': 'ЭКО: дневник экологических привычек',
      'home': 'Мои привычки',
      'catalog': 'Каталог привычек',
      'stats': 'Статистика',
      'profile': 'Профиль и настройки',
      'achievements': 'Достижения',
      'eco_impact': 'Экологический эффект',
      'settings': 'Настройки',
      'login': 'Войти',
      'signup': 'Регистрация',
      'email': 'Email',
      'password': 'Пароль',
      'forgot_password': 'Забыли пароль?',
      'no_habits_today': 'Нет привычек на сегодня',
      'add_habit': 'Добавить привычку',
      'today': 'Сегодня',
      'completed': 'Выполнено',
      'total': 'Всего',
      'streak': 'Серия',
      'week': 'Неделя',
      'month': 'Месяц',
      'all_time': 'За всё время',
      'export': 'Экспорт',
      'export_pdf': 'Экспорт в PDF',
      'export_subtitle': 'Отчёт по привычкам и эко-эффекту',
      'dark_mode': 'Тёмная тема',
      'notifications': 'Уведомления',
      'test_notification': 'Тестовое уведомление',
      'test_notification_subtitle': 'Проверить работу уведомлений',
      'notification_sent': 'Уведомление отправлено',
      'sign_out': 'Выйти из аккаунта',
      'change_password': 'Сменить пароль',
      'save': 'Сохранить',
      'cancel': 'Отмена',
      'delete': 'Удалить',
      'edit': 'Редактировать',
      'search': 'Поиск',
      'search_habits': 'Поиск привычек...',
      'water_saved': 'Воды сохранено',
      'energy_saved': 'Энергии сэкономлено',
      'co2_prevented': 'CO₂ предотвращено',
      'language': 'Язык приложения',
      'account': 'Аккаунт',
      'version': 'Версия 0.0.2',
      'confirm_exit': 'Выход',
      'confirm_exit_msg': 'Вы уверены, что хотите выйти?',
      'exit': 'Выйти',
      'progress_today': 'Прогресс на сегодня',
      'all_done': '✓ Всё выполнено!',
      'completed_percent': 'выполнено',
      'selected': '✓ Выбранные',
      'add': 'Добавить',
      'nothing_found': 'Ничего не найдено',
      'create_habit': 'Создать привычку',
      'select_period': 'Выберите период',
      'report_content': 'Содержимое отчёта',
      'export_to_pdf': 'Экспортировать в PDF',
      'exporting': 'Экспорт...',
      'select_date_range': 'Выбрать даты',
      'login_title': 'Дневник эко-привычек',
      'login_subtitle': 'Войдите, чтобы продолжить',
      'signup_title': 'Создать аккаунт',
      'signup_subtitle': 'Присоединяйтесь к зелёному движению!',
      'no_account': 'Нет аккаунта?',
      'already_have_account': 'Уже есть аккаунт?',
      'enter_email': 'Введите email',
      'invalid_email': 'Некорректный email',
      'enter_password': 'Введите пароль',
      'confirm_password': 'Подтвердите пароль',
      'passwords_not_match': 'Пароли не совпадают',
      'min_6_chars': 'Минимум 6 символов',
      'error_generic': 'Ошибка',
      'forgot_password_title': 'Восстановление пароля',
      'forgot_password_hint': 'Введите email, и мы отправим ссылку для восстановления пароля',
      'email_sent_title': 'Письмо отправлено! Проверьте вашу почту.',
      'email_sent_success': 'Письмо успешно отправлено!',
      'email_sent_desc': 'Проверьте почтовый ящик и следуйте инструкциям в письме',
      'back_to_login': 'Вернуться ко входу',
      'send_email': 'Отправить письмо',
      'eco_impact_tooltip': 'Экологический эффект',
      'profile_empty_today': 'У вас пока нет привычек на сегодня',
      'profile_empty_day': 'Нет привычек на этот день',
      'add_from_catalog': 'Добавьте привычки из каталога',
      'pick_another_day': 'Выберите другой день',
      'add_habits': 'Добавить привычки',
      'stats_empty': 'Добавьте привычки, чтобы увидеть статистику',
      'weekly_progress': 'Выполнение за неделю',
      'monthly_progress': 'Выполнение за месяц',
      'by_category': 'По категориям',
      'streak_days': 'дн.',
      'achievements_check': 'Проверить достижения',
      'your_progress': 'Ваш прогресс',
      'unlocked': 'Разблокировано',
      'percent': 'Процент',
      'new_achievement': '🎉 Новое достижение!',
      'great': 'Отлично!',
      'all_time_with_emoji': '🌍 За всё время',
      'month_with_emoji': '📅 За месяц',
      'week_with_emoji': '📊 За неделю',
      'today_with_emoji': '☀️ Сегодня',
      'visual_equivalents': 'Визуальные эквиваленты',
      'trees_co2': 'Деревьев (поглощение CO₂)',
      'car_km_co2': 'Км на авто (эквивалент CO₂)',
      'led_hours': 'Часов работы LED-лампы',
      'baths_water': 'Ванн (эквивалент воды)',
      'water_short': 'Воды',
      'energy_short': 'Энергии',
      'habit_created': 'Привычка создана! ✓',
      'habit_added': 'Привычка добавлена! ✓',
      'create_habit_failed': 'Не удалось создать привычку',
      'add_habit_failed': 'Не удалось добавить привычку',
      'habit_name': 'Название привычки',
      'habit_name_hint': 'Например: Пить воду утром',
      'enter_habit_name': 'Введите название привычки',
      'description': 'Описание',
      'description_hint': 'Опишите вашу привычку',
      'category': 'Категория',
      'eco_effect_optional': 'Экологический эффект (опционально)',
      'water_liters': '💧 Вода (литров)',
      'energy_kwh': '⚡ Энергия (кВт·ч)',
      'co2_kg': '🌬️ CO₂ (кг)',
      'frequency': 'Периодичность',
      'reminder': 'Напоминание',
      'reminder_time': 'Время напоминания',
      'not_selected': 'Не выбрано',
      'habit_effect_per_completion': 'Экологический эффект за выполнение',
      'water_saved_full': '💧 Воды сохранено',
      'energy_saved_full': '⚡ Энергии сэкономлено',
      'co2_prevented_full': '🌬️ CO₂ предотвращено',
      'error_prefix': 'Ошибка',
      'current_password': 'Текущий пароль',
      'new_password': 'Новый пароль',
      'password_changed': 'Пароль изменён',
      'app_language_ru': 'Русский',
      'app_language_en': 'English',
      'report_item_completed_count': 'Количество выполненных привычек',
      'report_item_completion_rate': 'Процент выполнения',
      'report_item_streaks': 'Серии выполнения',
      'report_item_eco_effect': 'Экологический эффект',
      'report_item_habit_details': 'Детализация по привычкам',
      'pdf_app_title': 'Дневник экологических привычек',
      'pdf_report_period': 'Отчёт',
      'pdf_overall_stats': 'Общая статистика',
      'pdf_habits_count': 'Привычек',
      'pdf_done_count': 'Выполнено',
      'pdf_percent': 'Процент',
      'pdf_streak': 'Серия',
      'pdf_eco_impact': 'Экологический эффект',
      'pdf_water_saved': 'Воды сохранено',
      'pdf_energy_saved': 'Энергии сэкономлено',
      'pdf_co2_prevented': 'CO₂ предотвращено',
      'pdf_visual_equivalents': 'Визуальные эквиваленты',
      'pdf_trees': 'Деревьев (поглощение CO₂)',
      'pdf_car_km': 'Км на авто (эквивалент CO₂)',
      'pdf_led_hours': 'Часов работы LED-лампы',
      'pdf_baths': 'Ванн (эквивалент воды)',
      'pdf_habit_details': 'Детализация по привычкам',
      'pdf_habit': 'Привычка',
      'pdf_category': 'Категория',
      'pdf_completions': 'Выполнений',
      'pdf_footer': 'Создано в приложении «Дневник экологических привычек»',
      'pdf_report_file_prefix': 'eco_habit_report',
      'day_mon': 'Пн',
      'day_tue': 'Вт',
      'day_wed': 'Ср',
      'day_thu': 'Чт',
      'day_fri': 'Пт',
      'day_sat': 'Сб',
      'day_sun': 'Вс',
      'cat_water': 'Вода',
      'cat_energy': 'Энергия',
      'cat_waste': 'Отходы',
      'cat_transport': 'Транспорт',
      'cat_consumption': 'Потребление',
      'cat_nature': 'Природа',
    },
    'en': {
      'app_title': 'ECO: Eco Habit Diary',
      'home': 'My Habits',
      'catalog': 'Habit Catalog',
      'stats': 'Statistics',
      'profile': 'Profile & Settings',
      'achievements': 'Achievements',
      'eco_impact': 'Eco Impact',
      'settings': 'Settings',
      'login': 'Login',
      'signup': 'Sign Up',
      'email': 'Email',
      'password': 'Password',
      'forgot_password': 'Forgot password?',
      'no_habits_today': 'No habits for today',
      'add_habit': 'Add habit',
      'today': 'Today',
      'completed': 'Completed',
      'total': 'Total',
      'streak': 'Streak',
      'week': 'Week',
      'month': 'Month',
      'all_time': 'All time',
      'export': 'Export',
      'export_pdf': 'Export to PDF',
      'export_subtitle': 'Habit and eco-impact report',
      'dark_mode': 'Dark mode',
      'notifications': 'Notifications',
      'test_notification': 'Test notification',
      'test_notification_subtitle': 'Check notifications work',
      'notification_sent': 'Notification sent',
      'sign_out': 'Sign out',
      'change_password': 'Change password',
      'save': 'Save',
      'cancel': 'Cancel',
      'delete': 'Delete',
      'edit': 'Edit',
      'search': 'Search',
      'search_habits': 'Search habits...',
      'water_saved': 'Water saved',
      'energy_saved': 'Energy saved',
      'co2_prevented': 'CO₂ prevented',
      'language': 'App language',
      'account': 'Account',
      'version': 'Version 0.0.2',
      'confirm_exit': 'Sign out',
      'confirm_exit_msg': 'Are you sure you want to sign out?',
      'exit': 'Sign out',
      'progress_today': 'Today\'s progress',
      'all_done': '✓ All done!',
      'completed_percent': 'completed',
      'selected': '✓ Selected',
      'add': 'Add',
      'nothing_found': 'Nothing found',
      'create_habit': 'Create habit',
      'select_period': 'Select period',
      'report_content': 'Report contents',
      'export_to_pdf': 'Export to PDF',
      'exporting': 'Exporting...',
      'select_date_range': 'Select dates',
      'login_title': 'Eco Habit Diary',
      'login_subtitle': 'Sign in to continue',
      'signup_title': 'Create account',
      'signup_subtitle': 'Join the green movement!',
      'no_account': 'No account?',
      'already_have_account': 'Already have an account?',
      'enter_email': 'Enter email',
      'invalid_email': 'Invalid email',
      'enter_password': 'Enter password',
      'confirm_password': 'Confirm password',
      'passwords_not_match': 'Passwords do not match',
      'min_6_chars': 'Minimum 6 characters',
      'error_generic': 'Error',
      'forgot_password_title': 'Password recovery',
      'forgot_password_hint': 'Enter your email and we will send a reset link',
      'email_sent_title': 'Email sent! Check your inbox.',
      'email_sent_success': 'Email sent successfully!',
      'email_sent_desc': 'Check your inbox and follow instructions in the email',
      'back_to_login': 'Back to login',
      'send_email': 'Send email',
      'eco_impact_tooltip': 'Eco impact',
      'profile_empty_today': 'You have no habits for today yet',
      'profile_empty_day': 'No habits for this day',
      'add_from_catalog': 'Add habits from the catalog',
      'pick_another_day': 'Pick another day',
      'add_habits': 'Add habits',
      'stats_empty': 'Add habits to see statistics',
      'weekly_progress': 'Weekly completion',
      'monthly_progress': 'Monthly completion',
      'by_category': 'By category',
      'streak_days': 'days',
      'achievements_check': 'Check achievements',
      'your_progress': 'Your progress',
      'unlocked': 'Unlocked',
      'percent': 'Percent',
      'new_achievement': '🎉 New achievement!',
      'great': 'Great!',
      'all_time_with_emoji': '🌍 All time',
      'month_with_emoji': '📅 Month',
      'week_with_emoji': '📊 Week',
      'today_with_emoji': '☀️ Today',
      'visual_equivalents': 'Visual equivalents',
      'trees_co2': 'Trees (CO₂ absorption)',
      'car_km_co2': 'Car km (CO₂ equivalent)',
      'led_hours': 'LED lamp hours',
      'baths_water': 'Bathtubs (water equivalent)',
      'water_short': 'Water',
      'energy_short': 'Energy',
      'habit_created': 'Habit created! ✓',
      'habit_added': 'Habit added! ✓',
      'create_habit_failed': 'Failed to create habit',
      'add_habit_failed': 'Failed to add habit',
      'habit_name': 'Habit name',
      'habit_name_hint': 'For example: Drink water in the morning',
      'enter_habit_name': 'Enter habit name',
      'description': 'Description',
      'description_hint': 'Describe your habit',
      'category': 'Category',
      'eco_effect_optional': 'Eco impact (optional)',
      'water_liters': '💧 Water (liters)',
      'energy_kwh': '⚡ Energy (kWh)',
      'co2_kg': '🌬️ CO₂ (kg)',
      'frequency': 'Frequency',
      'reminder': 'Reminder',
      'reminder_time': 'Reminder time',
      'not_selected': 'Not selected',
      'habit_effect_per_completion': 'Eco impact per completion',
      'water_saved_full': '💧 Water saved',
      'energy_saved_full': '⚡ Energy saved',
      'co2_prevented_full': '🌬️ CO₂ prevented',
      'error_prefix': 'Error',
      'current_password': 'Current password',
      'new_password': 'New password',
      'password_changed': 'Password changed',
      'app_language_ru': 'Russian',
      'app_language_en': 'English',
      'report_item_completed_count': 'Completed habits count',
      'report_item_completion_rate': 'Completion rate',
      'report_item_streaks': 'Streaks',
      'report_item_eco_effect': 'Eco impact',
      'report_item_habit_details': 'Habit details',
      'pdf_app_title': 'Eco Habit Diary',
      'pdf_report_period': 'Report',
      'pdf_overall_stats': 'Overall statistics',
      'pdf_habits_count': 'Habits',
      'pdf_done_count': 'Completed',
      'pdf_percent': 'Percent',
      'pdf_streak': 'Streak',
      'pdf_eco_impact': 'Eco impact',
      'pdf_water_saved': 'Water saved',
      'pdf_energy_saved': 'Energy saved',
      'pdf_co2_prevented': 'CO₂ prevented',
      'pdf_visual_equivalents': 'Visual equivalents',
      'pdf_trees': 'Trees (CO₂ absorption)',
      'pdf_car_km': 'Car km (CO₂ equivalent)',
      'pdf_led_hours': 'LED lamp hours',
      'pdf_baths': 'Bathtubs (water equivalent)',
      'pdf_habit_details': 'Habit details',
      'pdf_habit': 'Habit',
      'pdf_category': 'Category',
      'pdf_completions': 'Completions',
      'pdf_footer': 'Generated in Eco Habit Diary app',
      'pdf_report_file_prefix': 'eco_habit_report',
      'day_mon': 'Mon',
      'day_tue': 'Tue',
      'day_wed': 'Wed',
      'day_thu': 'Thu',
      'day_fri': 'Fri',
      'day_sat': 'Sat',
      'day_sun': 'Sun',
      'cat_water': 'Water',
      'cat_energy': 'Energy',
      'cat_waste': 'Waste',
      'cat_transport': 'Transport',
      'cat_consumption': 'Consumption',
      'cat_nature': 'Nature',
    },
  };

  String translate(String key) {
    return _localizedValues[locale.languageCode]?[key] ?? key;
  }

  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();
}

/// Extension для удобного перевода
extension LocalizedBuildContext on BuildContext {
  String tr(String key) {
    return AppLocalizations.of(this).translate(key);
  }
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    return ['en', 'ru'].contains(locale.languageCode);
  }

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}
